### PR TITLE
Git security breach

### PR DESCRIPTION
**Pull request by hugobessaa**
Hey guys :smile: 

During the weekend I learned that git has a pretty simple, but yet dangerous "security breach".

The problem is:

1. The user changes the commit author with the `--author` option
1. This commit introduces a bug in the behalf of the other author
1. Crackers explore this breach
1. Audits will not be able to know who was the commit author

This is something large open source projects, like Linux, worry about. However, with the always increasing number of employees and contractor developers here I think we should worry about this too.

With git 1.7.2, anyone can sign commits and tags with their [GPG key](https://gnupg.org/).

The post [Git Horror Story](http://mikegerwitz.com/papers/git-horror-story.html) shows an user case that is very near what is possible here, and also shows many ways project maintainers can ensure all commits are signed and valid.

It's pretty easy to sign commits with your gpg key:

1. Install gpg if you don't have it: `brew install gpg`
1. Create a gpg key if you don't have one: `gpg --gen-key` (the default options are just fine)
1. Run `gpg --list-secret-keys | grep ^sec` and copy the code after the first `/`.
1. Use `git config --global user.signingkey <key>`, changing `<key>` with the copied code
1. Use `git commit -S` to sign your commits. You can also sign existing commits with `git commit -S --amend`.

After this initial setup, one can sign any valid commits, even the ones they don't wrote.

I added `git commit -S` to my `gc` zsh alias, so that I never forget to sign my commits.

It will them be the maintainer job to audit and make sure everyone is signing their commits and that every commit is valid. This job can be easy using CI and some shellscripts.

I really think this is something we should look for.

*Note the fake commits below. I authored them and changed the author to be some guys in our team. That's dangerous.*

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
well

**Comment by rafaelrinaldi** [comment]
well

**Comment by raphaelfabeni** [comment]
dammit

**Comment by hugobessaa** [comment]
So should we create security policies for our repositories?

From now on, I'm signing all my commits with my public key.

My public key is available at my [website](https://hugobessa.com.br/gpg-public-key.asc). You can also fetch it from the the [MIT](http://pgp.mit.edu/pks/lookup?op=get&search=0xC247091E340BB459) and [Ubuntu](http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC247091E340BB459) keyservers.

To show commits with gpg signatures, run: `git log --show-signature`

**Pull request closed without merging**
