### PR TITLE
Use double quotes

### PR DESCRIPTION
**Pull request by brenopolanski**

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@brenopolanski What's up with this pull request? Are you serious?

**Comment by brenopolanski** [comment]
Hey @rafaelrinaldi.

Well.. in your styleguide you has: https://github.com/netshoes/styleguide/blob/master/markup/README.md#1.1. So I think that someone forgot of add double quotes ;)

**Comment by rafaelrinaldi** [comment]
@brenopolanski Oh, I see what you mean. This is a documentation file though, it's fine the way it is. I will merge your changes anyway...
Thanks for the contribution and please at least add a description next time, just to make everybody's life easier :+1:

**Comment by brenopolanski** [comment]
@rafaelrinaldi Sorry!!

**Comment by rafaelrinaldi** [comment]
@brenopolanski Nothing to be sorry about :smile: Thanks for the contribution!

**Comment by rafaelrinaldi** [comment]
@mauriciosoares can you please, merge this? :grimacing:

**Comment by mauriciosoares** [comment]
yup! :smile:

**Pull request merged**
