### PR TITLE
feat(scm): Adding new commit message standard

### PR DESCRIPTION
**Pull request by weslleyaraujo**
as discussed in #48 

😊

### CODE REVIEW

**Comment by raphaelfabeni** [comment]
For me it's ok!
I wanna try it..
Goooo!

**Comment by raphaelfabeni** [comment]
Whereeeee are the guys?

**Comment by weslleyaraujo** [comment]
intervention-s08-e013-rocky-crac

**Comment by rafaelrinaldi** [comment]
:rocket:

**Pull request merged**
